### ISSUE TITLE
Some thoughts and little issues with new release

### ISSUE THREAD

**Issue by JonnyRedHed** [snowie2000/mactype#148]
First, thanks snowie for all your hard work on this new update.  (_please consider secure donations_)

A few minor things.

Installed the new update but when I chose 'custom', all the component names and descriptions are not in English... or have an English option there.  So kind of hard to know what is what from an English speaking/reading perspective.

What does 'complete' install option do?  what extra things are installed out of curiosity.

The preview stage,  I choose registry option.  But the preview stage still kind of hard to understand the icons... apart from the one I usually choose for Win7 on large plasma TV screen  (LCD W7).

Is there anyone who can supply English translations to the 'custom' install option.   And also expand upon the 'preview' sections a little.

Apart from that,  it installed ok.  Although I did first try the complete option but that failed to find or load some DLL.  (win7)  so went back and used 'typical' option which installed ok, then rebooted.

> One last thing,   what entries in the start parameters of Opera/Chrome/FF etc should be there now post new update.

**Comment by Vassile-D** [comment]
**Custom Setup**

MacType:
- Config Templates: MacType configuration examples.
- XMac Config Templates: XMac configuration examples.
- Config Editor: GUI version of MacType configuration editor.
- MacType 64-bit: 64-bit (x64) support for MacType. Requires Windows Vista and later versions of Windows.
- Install to system folder(s): *No description. Pretty ambiguous option. What system folder? System32? Program Files? Needs developer to provide more info.*

GDIBench: Benchmark tool.

**Comment by JonnyRedHed** [comment]
How to get it working with utorrent.  All that white space and thin font on a large screen makes it hard viewing.

**Comment by snowie2000** [comment]
Install to system folder(s) 
This will copy easyhk32.dll to system32(x86)/syswow64(x64) and easyhk64.dll to system32(x64 only)
Actually, they are not real copies, they are just hardlinks.

To see this option, you have to have a system newer than win8.

PS: The reason these options are in Chinese is mainly because I don't know how to do this in multi-languages :(

**Comment by Vassile-D** [comment]
@snowie2000 Since you're using Advanced Installer to make the wizard, this webpage may help you:

http://www.advancedinstaller.com/user-guide/tutorial-languages.html

**Comment by snowie2000** [comment]
@Vassile-D 
Thank you!
@JonnyRedHed 
And this options only works if you install mactype to the system driver. Because hardlinks can't be made across drivers and it is meaningless to do this when mactype is not installed in program files, windows 10/8 won't load them if they are not in these special folders.

**Comment by JonnyRedHed** [comment]
So on win7x64 which is the best install option.   Once installed and first run I usually choose 'registry',  is this the one I want for seamless use across win7 ?   I prefer the best set-and-go option, but never seems to catch utorrent of some other programs such as Diskeeper 2011, Windows live mail 2009.

**Comment by snowie2000** [comment]
@JonnyRedHed 
There is no best option but most suitable option.
For most seamless experience, registry.
For safest option (less crash, best compatible and flexible), standalone mode.
Service mode is the balance of the above two, not so safe as standalone mode but more seamless, yet as seamless as registry mode~
Hard to make choice, isn't it.

I don't use Diskeeper or windows mail personally, but I guess they are built based on WPF or DirectWrite tech which is not fully supported by MacType in the version. Though I provided some sort of tweaks to it, it really does nothing good on Win7. Because Microsoft is not updating DirectWrite for Windows7 anymore. DW in Windows 10 is alot better than it is in Win7, but as you know, win10 is awful, and anyway, DW is still so bad after all. 

And for browsers, I know nothing about Opera. I've heard that you can not turn Directwrite off in Opera.
For chrome newer than 52, there is no way to turn off DW. If you don't want to see the bad rendering result, stick with chrome 51 or install centBrowser instead.
For FF, open url about:config, and turn direct2d off will do the trick.

**Comment by JonnyRedHed** [comment]
For now I'll stick with registry and LCD W7.   I might give standalone mode a go though.

What matters is mactype works for most of Win7 for me :)


So, that mactype patch that appeared elsewhere,  is that worth using on win7.  And that tweak you mention in the new release changelog, does that help on win7.

**Comment by snowie2000** [comment]
The new release of mactype is almost equivalent with old mactype + patch but with lots of other fixes.
That patch is useful for windows 10 users but not for win7 users.

**Comment by JonnyRedHed** [comment]
Poor old Windows 7, getting left behind.   I'll maybe move to windows 10.5/11 ??  in 2020 when forced to when win7 updates end proper.

**Comment by Twilightssuperb** [comment]
Where to download official update by **snowie2000**?

**Comment by snowie2000** [comment]
mactype.net
On 周四, 9月 1, 2016 at 18:55, Twilightssuperb <notifications@github.com> wrote:
Where to download official update by snowie2000 ?

**Comment by snowie2000** [comment]
multi-lang installer released.
