### ISSUE TITLE
Is it possible to turn on/off automatically based on screen DPI?

### ISSUE THREAD

**Issue by krrr** [snowie2000/mactype#157]
mactype looks not better than cleartype at 96DPI, but looks much better at 144DPI. Is there a way to disable it automatically on low pixel density screens?

**Comment by snowie2000** [comment]
Not possible currently, but I've figured out an alternative way to do this in the developing version, see if it fits your need:

The reason you think that mactype does a better job on HiDPI is that due to the increase of pixel density, Windows actually increased the font size so that it can provide more details. Which means the size of font you see in HiDPI display is actually higher than low DPI display. 
I'll provide a new param called MinHeight, which will prevent mactype from rendering fonts smaller than give size. By using this param, you can disable mactype on small font. Once you move a windows to a HiDPI display, as Windows scales the font, mactype will back to work again.

**Comment by krrr** [comment]
@snowie2000 nice feature! can't wait to try it out

**Comment by krrr** [comment]
@snowie2000 So I found the param already exists, and this https://github.com/krrr/mactype/commit/146a213e2304208cb3c1a3e6fa941a386d908761 make it works. Tested on Per-Monitor Aware app. Should it be enough?

**Comment by snowie2000** [comment]
@krrr  I haven't tested this feature really. Thanks for your correction.

**Comment by krrr** [comment]
nice https://github.com/snowie2000/mactype/commit/5bdd8a9aee9e525ee75bb8f5ab27f3f94e37f580
