### ISSUE TITLE
Add support for Visual Studio 2015

### ISSUE THREAD

**Issue by masepi** [snowie2000/mactype#167]
Mac type does not work on VS 2015.
Windows 10 x64

**Comment by mxalbert1996** [comment]
I think it works with VS2015. You can let VS upgrade the project automatically. And I think you need to change the freetype dir in `Include Directories` (Project -> Properties -> VC++ Directories). But the problem is that the project is missing `dynCodeHelper.h` and `dynCodeHelper.cpp` so I can't get it compiled.

**Comment by masepi** [comment]
No, I am not about building MacType. I mean that text do not rendering in Visual Studio 2015 using MacType.

**Comment by mxalbert1996** [comment]
It works. Just add `DirectWrite=1` to the `General` section of `MacType.ini`. And perhaps you need to add `devenv.exe` to `ExcludeSub` section.

**Comment by mxalbert1996** [comment]
Screenshot:
![2016-09-05](https://cloud.githubusercontent.com/assets/9391933/18248011/9a080374-73a8-11e6-95c0-d600a7c6322c.png)

**Comment by mxalbert1996** [comment]
Screenshot:
![2016-09-05](https://cloud.githubusercontent.com/assets/9391933/18248067/e7a7d14a-73a8-11e6-8f10-464f9b2c4eef.png)

**Comment by masepi** [comment]
Thank you!
