### ISSUE TITLE
influence visual studio  compiled

### ISSUE THREAD

**Issue by vkyzmsj** [snowie2000/mactype#184]
version： MacTypeInstaller_2016_0904_0
# after installing this version software，If you use studio visual to compile the c++ project，  the compiler fails.Here is the error info：

hgeGUIMenuItem.cpp
GuiGameState.cpp
game.cpp
BasicGameState.cpp
Generating Code...
Linking...
# LINK : fatal error LNK1101: incorrect MSPDB120.DLL version; recheck installation of this product

the visual studio version is 2013， if you use vs2015， the error info also occurs again，but like this：
 LINK : fatal error LNK1101: incorrect MSPDB140.DLL version; recheck installation of this product。

After you uninstalling mactype，compiling will be ok， nothing is wrong。

**Comment by ccloli** [comment]
From my side, it works when using X64 but failed with X86.

By the way, I tried to exclude all the process of Visual Studio (like C/C++ Compiler, MSBuild, VSHub...) except Visual Studio itself, sometimes it works. But most of time, MSBuild is still using MacType, even it's excluded, which makes Visual Studio and CMake build failed.

Tested with MacType 1.2016.0904.0, I also tried MacType_patch but still no luck.

![Screenshot](https://cloud.githubusercontent.com/assets/8115912/20627783/4a48fe70-b35d-11e6-803d-b7317e9ef150.jpg)
(Sorry the screenshot is in Chinese, it said "MSBuild.exe has stopped working", and the window behind it showed that MSBuild.exe is ignored but it's still enabled MacType. This screenshot is clipped when configuring with CMake, but in fact it happens when building with Visual Studio, you can see the Microsoft Error Report program is running in background)

**Comment by snowie2000** [comment]
try ctp version from http://www.mactype.net/station/

**Comment by ccloli** [comment]
I tried MacType_CTP_161116.rar, and it seems work fine now, both Visual Studio and CMake work without crashing or outputting error. Thanks for your work!

**Comment by snowie2000** [comment]
You are most welcome.
