### ISSUE TITLE
Registry mode not applying AA in W10 AU

### ISSUE THREAD

**Issue by aridzephyr** [snowie2000/mactype#194]
Every other mode works

**Comment by adeldk** [comment]
Try disabling [secure boot](https://msdn.microsoft.com/en-us/windows/hardware/commercialize/manufacture/desktop/disabling-secure-boot?f=255&MSPPError=-2147217396) in your BIOS/UEFI settings.

Further reading: http://tieba.baidu.com/p/3633897427

**Comment by matthewadamsdk** [comment]
@adeldk - thankyouthankyouthankyou! :-)

I've always run mactype in registry mode until upgrading to Win10 AU, but after the upgrade I couldn't get registry mode to work - even after installing the latest version of mactype.

But sure enough - going into Bios and disabling Secure Boot solved the problem.

The link you attached says it nicely: "Secure Boot helps to make sure that your PC boots using only firmware that is trusted by the manufacturer." I guess Dell hasn't heard about mactype. :-p

 @snowie - you might want to mention to other users (maybe in the wizard) that Secure Boot has to be disabled in order to run mactype in registry mode.

![bios_nosecureboot](https://cloud.githubusercontent.com/assets/22302334/18928178/5a25602a-85bf-11e6-927c-1126c87a57f2.JPG)

**Comment by aridzephyr** [comment]
can confirm as well, registry mode works after disabling secure boot, thanks @adeldk! and @snowie2000 you probably want to add this to the mactype setup instructions, thanks for all your hard work!

**Comment by snowie2000** [comment]
I'll add this reminder to the wizard at a later time.
