### ISSUE TITLE
Ridiculous amount of file activity caused by MacType

### ISSUE THREAD

**Issue by warpsprung** [snowie2000/mactype#239]
On my machine when executing 100 forks of cmd it takes 7 seconds with MacType enabled:
cmd /c for /l %a in (1,1,100) do @cmd /c rem

When MacType is disabled it takes the normal 1 second. This is slowing down my SW builds enormously.

I used ProcMon to filter the cmd.exe events and noticed enormous file activity caused by MacType e.g. accessing of the currently active ini file:
http://superuser.com/questions/453655/command-prompt-takes-7-8-seconds-to-load-in-windows-7

**Comment by IceMan81** [comment]
In what mode do you run Mactype?

**Comment by warpsprung** [comment]
I'm running it in Tray mode.

**Comment by IceMan81** [comment]
Try registry mode. I observed that there was significant improvement in
performance in registry mode

**Comment by snowie2000** [comment]
@IceMan81 Registry mode won't do the magic.
The performance degradation is expected. Every time you start a new cmd.exe, MacType will have to load everything it needs for that new cmd.exe. This includes a profile read, a freetype font engine initialization, a registry fontlink scan and some pre-calculation. Which is actually not quite a big overhead for normal processes, but you start and stop processes really frequently, it becomes definitely considerable. 

In CTP build of MacType, MacType will only be fully loaded if Gdi32.dll is loaded (which is responsible for most GUI operation), which significantly improves command line application performance, but not cmd itself, because although cmd is a commandline program, it loads GDI dlls.

For the problem you faced, unload mactype for certain executables will be the only solution. (ExcludeModule won't do the job).

**Comment by warpsprung** [comment]
Just for completeness: Test with Registry mode yielded the same result.
@snowie2000 Thanks for the explanation!
Would it be possible to:
- Exclude cmd.exe internally in MacType?
- Don't load the INI file over and over again, but cash its contents - same could be done for the registry scan, though I think the file access slows things down more

**Comment by snowie2000** [comment]
@warpsprung 

- You can just write cmd.exe in UnloadDll section to the main profile "MacType.ini", settings here will be applied to all profiles.
- INI content is indeed cached, but every cmd.exe is a new start, memory cache doesn't work across processes. In CTP version, reading ini files is way faster than before. I used a custom ini reader to achieve this. But anyway, accumulation of every tiny bit of delay leads to big overhead if repeated too many times.

**Comment by warpsprung** [comment]
[UnloadDll]
cmd.exe 

Writing this into the MacType.ini crashed my ConEmu console. 
Then I copied the CTP version files from here: http://mactype.net/station/ over my existing installation and it worked. Now my SW build does not even take a second more time than without MacType!
Even without unloading cmd.exe this CTP version is at least 50% faster in my SW build than before.

Good work! Thanks!
