### ISSUE TITLE
Font weight issues with Roboto Mono 

### ISSUE THREAD

**Issue by Jeremiidesu** [snowie2000/mactype#268]
It seems that there is a weight selection problem with Roboto Mono
![roboto mono](https://puu.sh/vpcD7/3d14b5364b.png)
![roboto mono 2](https://puu.sh/vpcE1/13ab7994c7.png)
As you can see, all the non-bold weights (Medium, Regular, Light and Thin) are all the same fonts.
When the gamma value of the profile makes the text lighter, sometimes the Light or Thin variant is loaded as "all but bold"
All the other fonts from my library (including other downloaded ones such as Exo 2, Roboto, Gravity, (all three downloaded from google fonts)) are selecting their fonts fine

More screenshots:
Roboto Mono Thin: 
![roboto mono thin](https://puu.sh/vpcQh/941e720edf.png)
Roboto Mono Medium: 
![roboto mono medium](https://puu.sh/vpcRq/783a56b08e.png)
Roboto Mono Bold: 
![roboto mono bold](https://puu.sh/vpcSH/721c48c86f.png)

WordPad is also affected, leading me to think it's a "systemwide" selection problem:
![wordpad](https://puu.sh/vpcXS/21462e7821.png)

**Comment by Jeremiidesu** [comment]
I could add that this font loading problem does _not_ occur in the MacType Tuner.

**Comment by snowie2000** [comment]
![qq 20170531111307](https://cloud.githubusercontent.com/assets/11767189/26614326/313de544-45f2-11e7-9af9-8c94d47ff6d4.png)
As you can see, this problem happens to Roboto Mono in font selection dialog even without MacType (sorry that my Windows is in Chinese).
Since MacType's principle is that it will always follow Windows GDI standard to get best compatibility, it is quite normal that you will get the same result.

**Comment by Jeremiidesu** [comment]
Oh, I see. I never noticed it before with Windows so I assumed it was MacType's fault but it isn't. Thanks for the reply!
