### ISSUE TITLE
MacType_CTP_170307_W10 comes with a malware

### ISSUE THREAD

**Issue by ced64k** [snowie2000/mactype#276]
I have a BitDefender alert if I try to download latest CPT release at this url: http://mactype.net/station/MacType_CTP_170307_W10.rar

The page you are trying to access contains malware.
**Gen:Variant.Adware.Razy.170350**

No alert with older releases.

**Comment by snowie2000** [comment]
No hack actions detected on my server. So I believe it's just a false alarm.
However, if you do have concern about the warning, do not use it.

**Comment by adelduprat** [comment]
[False positive.](https://www.virustotal.com/en/file/fca685534f64b68827c3c6bc3af8b9ad627cdceb2e59d78a87f4fd4830943bf9/analysis/1491699905/)

**Comment by IceMan81** [comment]
I got the same alert yesterday. What is Gen:Variant.Adware.Razy.170350? I don't recall seeing this file before in the MacType folder. 
The W10 rar file does not contain this file. 
I think this file got added to the MacType folder during some usage, not clear how.
I deleted this file, because my antivirus quarantined this file and deleted MacType.dll
To fix, I deleted Gen:Variant.Adware.Razy.170350 and restored MacType.dll

**Comment by snowie2000** [comment]
I don't see any suspicious file in my archive. Try upload the file you downloaded from my site to see if they are identical.

**Comment by ced64k** [comment]
From y side I can't download the file, it's blocked by Bitdefender Endpoint Security.

**Comment by RitzyBusiness** [comment]
Going to echo snowie but I just downloaded this a moment ago with zero issue.  Bit defender nor firefox detected anything malicious with this file.  Scanning manually with bit defender yielded no issue as well.

More then likely safe to call it a false alarm.  Certain paranoid modes might dislike hooking dll's.

**Comment by ced64k** [comment]
Today the same link is working and not detected as malware
