### ISSUE TITLE
After upgrading to creator update, font rendering in intellij is weird.

### ISSUE THREAD

**Issue by nichbar** [snowie2000/mactype#281]
I have applied the CTP patch.
The fonts in intellij looks weird.
I'm using consola as my editor font .
When i changed font size to 16 it looks like this
![image](https://cloud.githubusercontent.com/assets/7713080/26291345/3208dc2c-3ee0-11e7-9887-6f1d5ce92f9c.png)
When font size changed to 20 the rendering is fine
![image](https://cloud.githubusercontent.com/assets/7713080/26291471/19b9ea02-3ee1-11e7-87e7-af41601b3e1c.png)
Is that a bug ? If not, what should i do to make it work in size 16 ?

**Comment by snowie2000** [comment]
You should enable ClipBoxFix for java apps.

**Comment by IceMan81** [comment]
@snowie2000  @nichbar For which anti-aliasing mode does ClipBoxFix work? I didn't see any impact of ClipBoxFix when using Light+LCD (mode 4) in Intellij. Eventually I had to use Mode 2 (LCD) to get rid of any clipping issues. Does setting ClipBoxFix=1 enable it?

**Comment by nichbar** [comment]
@IceMan81 
I use Mode 4 and it works well in android studio which is based on Intellij. 
Here comes my script :
```
[Experimental@studio64.exe]
ClipBoxFix=1
```
You may replace studio64.exe with the process's name you wanna enable.

**Comment by snowie2000** [comment]
@IceMan81 ClipBoxFix is valid in all antialisemode, but due to a known bug of ctp build, per-application configuration is not work and the last line of profile is always omitted. :rofl: 
So, to make your setting effective, you have to write clipboxfix=1 under experimental global section instead of experimental@yourexe, and always add a line break at the end of file.

All these bugs will be solved in the final release.

**Comment by IceMan81** [comment]
@snowie2000 The issues with ligatures still exist. 
I think the issue is similar to this one. https://github.com/snowie2000/mactype/issues/282
