### ISSUE TITLE
Not an issue, but recreating gdipp settings in MacType?

### ISSUE THREAD

**Issue by jmbattle0** [snowie2000/mactype#284]
Hello,

I have used MacType on and off in the past, but after recently learning of the 2016 update, I have decided to install the software permanently - replacing gdipp, which unfortunately appears to no longer be in development.

I have tweaked the MacType settings .ini (from the default.ini base settings), but am unable to quite achieve the same appearance as my preferred gdipp settings.

I have attached both settings files, so would welcome any suggestions.  Are there some options in gdipp that directly relate to MacType?  I appreciate that, while both utilising FreeType, gdipp and MacType are different pieces of software, however I would very much like to recreate the FreeType appearance on my Windows PC with MacType, if possible.

Thank you for reading!

[gdipp_setting.xml.txt](https://github.com/snowie2000/mactype/files/1034842/gdipp_setting.xml.txt)
[TweakedJMB.txt](https://github.com/snowie2000/mactype/files/1034843/TweakedJMB.txt)

**Comment by sammilucia** [comment]
Hi @jmbattle0 ... i'm going to close this issue because it hasn't had any takers and we need to keep issues managed so we can focus on what needs to be done for next releases of MacType... maybe there are some forums where you might be able to get some help for this?

I believe a lot of the code for gdipp was updated in MacType so you should be able to get close, but maybe not perfect. If you can give me some screenshots of what you want to achieve I may be able to help 😊
