### ISSUE TITLE
Latest win10 pushed up ,making some questions

### ISSUE THREAD

**Issue by takfate** [snowie2000/mactype#285]
When I try to clear the RecycleBin ,the resource manager will crash.
More than this ,  the resource manager frequently crashes while doing some common operation.

**Comment by nichbar** [comment]
You may try CTP patch . [Issue 275](https://github.com/snowie2000/mactype/issues/275)

**Comment by ayukas** [comment]
CTP patch still have small issues with some of the system applications. 
Recently I got random arp.exe crash here and there caused by Mactype, it doesn't affect most usage of the system. 
But still kind of annoying as a stopping program notice jumping out when you playing full-screen game.

"Faulting application name: arp.exe, version: 10.0.15063.0, time stamp: 0x2ce2e69f
Faulting module name: MacType.dll, version: 0.0.0.0, time stamp: 0x5864a58f
Exception code: 0xc0000005
Fault offset: 0x00002b15
Faulting process id: 0x2684
Faulting application start time: 0x01d2dcf5f22fffc2
Faulting application path: C:\WINDOWS\SysWOW64\arp.exe
Faulting module path: C:\Program Files\MacType\MacType.dll
Report Id: 7bb88033-d369-4f0a-9970-4ef90d51539d"

**Comment by snowie2000** [comment]
Normally, arp.exe won't run automatically.
