### ISSUE TITLE
Multiple issues in version 1.17.614.0 released today

### ISSUE THREAD

**Issue by Wolfarelli** [snowie2000/mactype#291]
Hi Snowie, im afraid the new version is not working for me. (Windows 10 1703 build 15063.413)

- Frozen desktop
- No visible option to uninstall in the uninstaller.

I accepted the automatic update and it executed normally. Besides the not standard UI of the installer it was unusual that it asked to close dozens of applications that were using MacType at that time. I selected the option not to close them and to restart.

After the restart and log in, I couldn't get a working desktop, it was just frozen, taskbar visible but unresponsive. The solution was to restart 2 times the explorer.exe process. I tried to restart the PC but got the same frozen desktop and had to restart again the explorer.exe process twice.

Then I tried to unistall MacType from the Windows Control Panel. The uninstaller showed a install option and no uninstall option ¿? Tried to go to the configure install options expecting to deselect each module but it didn't let me unselect all. I continued anyway and restarted the PC. I could access my desktop normally again, but the program files are still there and the uninstall option too, and the system tray program still is there but disabled. ¿? Im gonna manually uninstall those files and going to go back to the previous version.

This is a screenshot of the uninstaller not letting me deselect the program to uninstall it.

[http://imgur.com/a/iRUa1](url)

Regards

Wolfarelli

**Comment by snowie2000** [comment]
I'm sorry to hear it.
The reason that you can only see install button instead of uninstall button is that the previous update is unsuccessful. 
The installer will search registry for installation information, only when it found certain registry keys will it consider your operation as a uninstall. And it is totally normal for an installer/updater to ask you to close programs that are using the files it needs to replace, or you have to restart to let windows do the job. 
MacType is deeply hooked into so many processes that without a restart, it is almost impossible to overwrite old files. And of course, there can be bugs with my installer.

My recommendation is that you can enter safemode, and delete all the mactype files, then you reboot back to normal system and do a clean install, and see if it solves your problem.

**Comment by Wolfarelli** [comment]
Thank you for your reply Snowie.

I tried uninstalling this time succesfully using the uninstaller I found in C:\Program Files\MacType\updates folder, and then manually deleted whatever files were left. Then I tried to run the new installer downloaded from mactype.net but it was blocked by windows smartscreen, and for some reason didn't had the option to run anyway.

So I installed again the old version (without patches) and then updated to the new version from there. Its working now.

Thank you Snowie.
