### ISSUE TITLE
Is it better to use FreeType hinting as compared with ClearType hinting? (Mactype 2017_0628_0)

### ISSUE THREAD

**Issue by Twilightssuperb** [snowie2000/mactype#312]
Accidentally I set HintingMode=2 (with AntiAliasMode=4) in win7.ini and, seems, activated FreeType hinting. So fonts look pretty better now, it completely remind me OS X view. My eyes finally chill! As I've read at Wiki, HintingMode=2 looks better solution as compared with 0 or 1 value—both of them don't give me the desired effect. Is it right point or I'm wrong?

**Comment by snowie2000** [comment]
0 means no hinting is applied while 1 means use font embedded hinting before trying to apply auto hinting. 
It is hard to say which is better. If freetype auto hinting is always the best, why does the manual hinting still exist today? however, freetype auto hinter (which is now actually contributed by adobe)  is really good in fact. It generates quite decent hinting in many cases, and is sometimes better than manual hinting, and definitely way better than ClearType hinting.
If you don't have a high DPI monitor and prefer the shape edged text, yes, freetype hinting is probably one of your best friends.

**Comment by rudolphos** [comment]
Does this work on Windows 10 and default profile?

**Comment by snowie2000** [comment]
This setting works on GDI with every version of Windows.
For DirectWrite, there is no freetype hinting available.

**Comment by IceMan81** [comment]
@snowie2000 Are you sure about HintingMode=0 means no hinting. I thought HintingMode=1 means no hinting. That's how you have documented it in the default.ini profile. 
Also see line 1307 in ft.cpp

https://github.com/snowie2000/mactype/blob/7d9ea877702dd1bd55502da68fd2408013637871/ft.cpp

**Comment by snowie2000** [comment]
Ah, sorry about that. You are absolutely right.

**Comment by Twilightssuperb** [comment]
@snowie2000, thanks for explanation. 😊

**Comment by rudolphos** [comment]
![image](https://user-images.githubusercontent.com/4366810/27717029-29cafa5c-5d4b-11e7-9cd3-e13aa487f7c1.png)
Hinting 1


![image](https://user-images.githubusercontent.com/4366810/27717045-3f897102-5d4b-11e7-91bc-a5272cecac90.png)

Hinting 2


Default profile on Windows 10

**Comment by snowie2000** [comment]
@rudolphos You scaled up the image with linear interpolation which kills all the details.
Hinting is born for sharpness, not for smoothness. 
H2 is less smoother than H1, but H1 is blurrier than H2. It depends on which way you prefer.

**Comment by kriston** [comment]
FreeType auto hinting in "Slight" mode offers the best shapes and the most clarify with subpixel hinting.  With the newest ClearType-optimized fonts (Calibri, etc.) the FreeType manual hinter (the TrueType hinter) should not be used.  The auto hinting in "Slight" mode is possibly the best.

**Comment by Nek80** [comment]
> FreeType auto hinting in "Slight" mode offers the best shapes and the most clarity with subpixel rendering. 

I totally agree. But how do we enable "Slight" mode with MacType 1.2017.628.0? (It certainly does not render the same as Slight mode in my Arch Linux computer.)

**Comment by kriston** [comment]
Maybe the Arch Linux has the Infinality patches.  The reason I mention
that is because the most popular Ubuntu ppa for Infinality FreeType (and
other distributions) was derived from the Arch Linux patches.  I
inquired here about Infinality patches in MacType but haven't heard
back.  For Infinality, "Slight" gives the best shapes.  It uses the
FreeType Autohinter and actually looks worse with the bytecode hinter
especially with the newer Microsoft ClearType fonts which rely on
enhanced hinting instructions that were not implemented in FreeType.

On 2017-08-24 04:25 AM, Nek80 wrote:

>> FreeType auto hinting in "Slight" mode offers the best shapes and the most clarity with subpixel rendering.
> 
> I totally agree. But how do we enable "Slight" mode with MacType 1.2017.628.0? (It certainly does not render the same as Slight mode in my Arch Linux computer.) 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/snowie2000/mactype/issues/312#issuecomment-324568528
[2]

**Comment by snowie2000** [comment]
#351 I explained something in this thread.

**Comment by kriston** [comment]
Thank you for the note!  I knew there was something special happening
with MacType's rendering and I'm so happy to see that Infinality (well,
most of it) is officially in FreeType now.  My Linux computers are using
custom-built Infinality FreeType because they were built before FreeType
included the patches (and now supports ClearType properly).

Thanks again!

On 2017-08-24 09:47 PM, snowie2000 wrote:

> #351 [1] I explained something in this thread. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/snowie2000/mactype/issues/351
[2]
https://github.com/snowie2000/mactype/issues/312#issuecomment-324802374
[3]
