### ISSUE TITLE
Making Mactype work in Opera

### ISSUE THREAD

**Issue by JonnyRedHed** [snowie2000/mactype#340]
Anyone know how to do this.

Adding `--disable-direct-write --disable-directwrite-for-ui` on start up does not appear to work.

**Comment by RitzyBusiness** [comment]
Last I recall, and a reason I ditched opera within the first hour of installing is there is no way to fully disable whatever font rendering it uses.  Cent, which is based off Chromium does work with those tweaks.

**Comment by JonnyRedHed** [comment]
So there's no way to make mactype work in Opera at the moment.

**Comment by RitzyBusiness** [comment]
Far as it is designed right now, there seems to be no way to make it work with Opera at this moment.  But perhaps someone will design a solution, or the opera devs will allow further customization.

I cant go back to using a browser or system without mactype either.  Which is why I chose an alternative solution (I find Chrome based solutions in general render text better then firefox which further helped my choice)

**Comment by sammilucia** [comment]
Opera is now Chromium based, unfortunately it's up to them whether they still support GDI from Chromium.

@RitzyBusiness @JonnyRedHed Please see the latest release notes, I've been using CentBrowser for a few years with GDI rendering and it works great 😊 https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2

Closing as duplicate #427

**Comment by JonnyRedHed** [comment]
So thats that then.  I'll continue to ask Opera devs.

**Comment by Lucire** [comment]
Here’s the strange thing: as of March 2020, MacType works perfectly with Opera and Opera GX for me. I’ve read all these threads about how it shouldn’t work with Chromium any more, and how the Directwrite-disable option was removed back in 2016, but since switching to Opera GX in January 2020 I’ve not had a problem. I used Vivaldi from September 2017 to January 2020 without any problems, too, and it was only when I updated it (to v. 2.10) in January that I began having type-rendering issues. It tells me that despite the changes in Chromium, something is still allowing me to have MacType-compatible browsers.
