### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1711700938** [snowie2000/mactype#410]
安装mactype后，鼠标右键桌面个性化或者桌面设置，会出现错误，windows设置经常性打不开。因为电脑经常出现这种情况，花了好长时间才发现是mactype的问题。很喜欢mactype希望能够解决。

**Comment by snowie2000** [comment]
请提供详细的信息，如系统，版本号，如果有错误日志请最好一起提供

**Comment by 1711700938** [comment]
Win10家庭版64位，最新版本。
发送自 Windows 10 版邮件应用

发件人: snowie2000
发送时间: 2018年3月23日 17:43
收件人: snowie2000/mactype
抄送: 1711700938; Author
主题: Re: [snowie2000/mactype] bug (#410)

请提供详细的信息，如系统，版本号，如果有错误日志请最好一起提供

**Comment by vimcaw** [comment]
我一直都遇到过这个问题，可能是 hook 系统界面渲染的问题，或者渲染 DirectWrite 的兼容问题。

暂时的解决办法：停用对系统设置界面的渲染
先停用：
![disable](https://user-images.githubusercontent.com/21964227/37943427-13845318-31aa-11e8-9a11-1ac3410c5b2d.png)
再排除，这样下次就不会渲染了：
![exclude](https://user-images.githubusercontent.com/21964227/37943444-2749ad3a-31aa-11e8-935e-17a75959b421.png)

或者直接把 DirectWrite 渲染关闭了：
配置文件里：
```ini
DirectWrite=0
```

相关问题： #344 #223

**Comment by 1711700938** [comment]
好的，谢谢！

发送自 Windows 10 版邮件应用

发件人: Changsheng Zhu
发送时间: 2018年3月27日 10:39
收件人: snowie2000/mactype
抄送: 1711700938; Manual
主题: Re: [snowie2000/mactype] bug (#410)

我一直都遇到过这个问题，可能是 hook 系统界面渲染的问题，或者渲染 DirectWrite 的兼容问题。
暂时的解决办法：停用对系统设置界面的渲染
先停用：

再排除，这样下次就不会渲染了：

或者直接把 DirectWrite 渲染关闭了：
配置文件里：
DirectWrite=0
相关问题： #344 #223

**Comment by sammilucia** [comment]
Hi @1711700938 , @vimcaw ... What anti-virus/antimalware software are you using?

If you're using one, please see the Known Issues in the readme and let us know if this helps https://github.com/snowie2000/mactype/blob/master/README.md

"If you're running 64 bit Windows, antimalware/antivirus software may conflict with MacType, because it sees MacType trying to modify running software. One possible workaround is to try running in Service Mode (recommended), or add HookChildProcesses=0 to your profile. See https://github.com/snowie2000/mactype/wiki/HookChildProcesses for an explanation"

**Comment by vimcaw** [comment]
@sammilucia Kaspersky Internet Security 2019

**Comment by vimcaw** [comment]
It looks likes fixed on v1.2018.09.17-beta2

**Comment by sammilucia** [comment]
Yay! thanks for letting me know @vimcaw 

closing issue. please let us know if you have any problems 😊
