### ISSUE TITLE
Cannot work with chrome 68?

### ISSUE THREAD

**Issue by narukamiko** [snowie2000/mactype#425]
My system is win10 and chrome version is 68.0. But the mactype cannot work with chrome? Is there any solution?

**Comment by snowie2000** [comment]
MacType works with Chrome, but not completely. You need to enable [DirectWrite](https://github.com/snowie2000/mactype/wiki/DirectWrite) support and it may still not seem good enough. 

To fully utilize its power of rendering, you have to use 3rd party chromium based browsers such as Cent browser which allows you to disable DirectWrite completely.

**Comment by narukamiko** [comment]
@snowie2000 Thanks.

**Comment by MaxCaulfield95** [comment]
![2018-08-19 14_26_38-settings](https://user-images.githubusercontent.com/8025617/44309342-2df55780-a3bd-11e8-9317-1ce9bd80e812.png)
This warning seems to appear every time I start Chrome now. Any way around it? Directwrite is enabled.

**Comment by SquirrelCoder** [comment]
I got this warning today in Chrome too.

**Comment by sammilucia** [comment]
Google Chrome's DirectWrite font engine is becoming less and less compatible with MacType. It's not a MacType problem, it's Chrome's mission to continually speed up page rendering - they're hacking the font engine themselves.

The solution is to use CentBrowser instead, which is a custom build of Chrome (https://www.centbrowser.com/). CentBrowser still contains the GDI font engine, so MacType works fully with it. To use it, disable DirectWrite in Centbrowser (chrome://flags/#disable-direct-write).

**Comment by snowie2000** [comment]
Obviously, there is no way to walkaround it as it is detected from Chrome side.
If what the incompatibility means is the sandbox integrity break, it is kind of true. Because Mactype has to break the sandbox to some extent to inject into its subprocess to make the rendering work.

For Directwrite compatibility, I don't think there will be a big problem in the near future unless the Chrome team decided to do the same hook themselves, for MacType only modifies some parameters of the DirectWrite engine, not replace it.

**Comment by sammilucia** [comment]
Perhaps the Chrome team has seen conflicts with MacType and blocked it.

Closing for now as the current workaround is to use CentBrowser.

**Comment by Lucire** [comment]
I had been using Vivaldi till recently as the bug began happening there, too. I switched to Opera GX (also Chromium-based) and it’s fine there.
