### ISSUE TITLE
Touhou series subtitles covered by black lanes.

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#440]
_Originally posted by @Mahayu in https://github.com/snowie2000/mactype/issues/427#issuecomment-417579254_

**Comment by sammilucia** [comment]
Possibly an alpha blending issue in MacType? Or in Touhou

**Comment by snowie2000** [comment]
The Touhou series has a lot of games, which game has the problem? Or all of them have it?

**Comment by Mahayu** [comment]
The screenshot was taken from thwiki.cc,

![default](https://user-images.githubusercontent.com/22572355/46721617-07111e80-cca6-11e8-9e34-1142296e4fc9.jpg)
![default](https://user-images.githubusercontent.com/22572355/46721618-07111e80-cca6-11e8-97dd-13078e92dcee.jpg)

Here is the oringal link:
https://thwiki.cc/%E5%AE%98%E6%96%B9%E6%B8%B8%E6%88%8F/%E9%94%99%E8%AF%AF%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95

It says the games after Touhou 10th will cause this bug.

**Comment by snowie2000** [comment]
![qq 20181010164757](https://user-images.githubusercontent.com/11767189/46724370-74c04900-ccac-11e8-8d74-ac49d30f29cf.png)
Here it is.
The black background problem is more or less solved. (by disabling support for 16bit graphic) But the texts are very hard to see using cleartype.

I believe the Touhou series used some sort of tricky method to get the text outline as VirtualBox did. (Virtualbox creates a special bitmap and draws texts on it, then it scans every pixel to look for the pixels with the highest bit modified, for GDI will modify every pixel it touched).
I searched for information about 16bit graphic and their RGB layout lies like:
`XRRR RRGG GGGB BBBB` meaning 2 bytes are used for one pixel (while 32bit uses 4bytes per pixel), and the first bit (marked as X) is not used).
I saw a lot of `00 80` like pixels in memory, so I guess it is the way the game extracts the text outline.

Since the 16bit graphic is rarely used today, I think we should put our focus on the things that most users use right now instead of writing another paint routine for rare cases. If you really need mactype to take effect on some old programs, maybe I can put an option somewhere to re-enable it.

**Comment by snowie2000** [comment]
Okay, Touhou 8th. Pretty readable texts. It's clear that the game did its own rendering to texts. It only uses GDI to get the shapes of texts (Why didn't they use more official ways like `GetGlyphOutline`?)
![untitled](https://user-images.githubusercontent.com/11767189/46784093-5a937300-cd5f-11e8-8beb-637a0be17c10.png)

**Comment by Mahayu** [comment]
Thanks for your effort. (And it wasn't Touhou 8th XD , it's just 12.3th.)
Anyway putting time on common issues is more important now, and I've put games in exclude lists.
Waiting for release. 👍

**Comment by sammilucia** [comment]
yay i think this is a good solution (disabling for 16 bit graphics)
