### ISSUE TITLE
On fresh install, MacWiz cannot select Registry Mode

### ISSUE THREAD

**Issue by sammilucia** [snowie2000/mactype#471]
To repro:
1. Clean all MacType installations and restart
3. Install MacType
3. Run MacWiz.exe and select Registry Mode

Expected Outcome:
- MacWiz.exe writes to AppInit_DLLs

Observed Outcome:
- MacWiz reports mode hasn't changed and does not write AppInit_DLLs

**Comment by sammilucia** [comment]
PS This is revenge for finding installer bug 😂

**Comment by snowie2000** [comment]
Okay, I'll check it tomorrow. 😅😅

**Comment by snowie2000** [comment]
I checked the code. The wizard determines the loading mode by several conditions (in the following order).
- If service `MacType` is found, Service mode is selected.
- If `mactype.dll` is found in `AppInit_DLLs` keys, Registry mode is selected.
- If autorun information is found in the registry:
  - If `LoadType` in the ini file is 1, Advanced mode is selected.
  - Otherwise, compatible mode is selected.
- Treat as manual mode.

With that said, if you can't change to registry mode, you must have something set in your registry already.

**Comment by sammilucia** [comment]
Ah okay, this will be a result of me having MacType64.dll in AppInit_DLLs while messing with the installer. I thought it was _only_ reading from the ini. Confirmed, closing
