### ISSUE TITLE
WPS Office 2019 渲染无效

### ISSUE THREAD

**Issue by wmjordan** [snowie2000/mactype#480]
最新的 MacType Beta4+DirectWrite 测试版，在 Win10 1809 上服务加载。
WPS Office 2019 无法渲染。

![default](https://user-images.githubusercontent.com/12182730/49124559-de95c000-f2f7-11e8-8fd6-7815f996f42a.png)

**Comment by snowie2000** [comment]
![qq 20181128103407](https://user-images.githubusercontent.com/11767189/49124945-400a5e80-f2f9-11e8-808d-1ee456d70e12.png)
请用向导的进程管理器查看wps的加载状态后再看是什么问题。我这边一切正常。

另外dw增强版的问题请不要另外新issue。

**Comment by snowie2000** [comment]
升级到新版本后出现问题，将会继续查找问题原因。感谢反馈。

Reproduced after upgrading to beta5. Investigating ...

**Comment by snowie2000** [comment]
问题已查明。新版WPS内部有一个krpt.dll文件，位置为`C:\Users\{UserName}\AppData\Local\Kingsoft\WPS Office\11.1.0.7989\office6\krpt.dll` 该文件会拦截LoadLibraryExW的调用，并检查加载的dll，其内置了一个dll黑名单，其中就包含有mactype.core.dll，遇到黑名单中的dll则禁止加载。
证据截图（该列表是加密的，直接搜索dll本身无法找到，运行中动态解密出来）：
![evidence](https://user-images.githubusercontent.com/11767189/49557804-cf3ff380-f943-11e8-86bb-5f71dcefc2d1.png)

理论上MacType可以绕过，但是既然这是金山公司刻意为之，我们并没有必要做这样的猫鼠游戏。如果您确有在wps上使用mactype的需求的话可以降级版本或者向金山公司反应。
此问题终结。

Problem found. There is dll named `krpt.dll` stored at `C:\Users\{UserName}\AppData\Local\Kingsoft\WPS Office\11.1.0.7989\office6\krpt.dll` which has hooked `LoadLibraryExW` and checks for every dll loaded.

The Dll has a built-in blacklist that if a dll is included, the loading procedure will be interrupted. MacType.core, however, is one of its entry.
The blacklist is encrypted and dynamically expanded during execution.

We could, in theory, walkaround this by using some "hack" methods, but because of the intention of filtering, we believe the correct way to solve this is to report your demands to the Kingsoft and ask them to re-consider the filtering process.

Closed as it won't be solved at MacType side. Notice will be added to the front page.

**Comment by wmjordan** [comment]
感谢您在这个问题上花费了这么多时间。
已经在WPS的卸载界面上向该公司反馈了上述问题。

**Comment by wmjordan** [comment]
今天晚上微软 Excel 在编辑过程中崩了，搞了小半小时的活几乎全丢。

于是又找了个 WPS 出来捣鼓一下。
之前网上流传的“将 WPS 设置成单组件运行模式可以支持 MacType 渲染”的方法已经无效。

但是，新版的 WPS 倒是给我们开了一扇窗。根据 snowie 前面的跟踪，WPS 的保护与 krpt 这个 DLL 有关。
经我用磁盘搜索发现，krpt 有一个配置文件，放在如下路径（请根据实际情况替换掉“当前系统用户名”和“版本号”）：
````cs
C:\Users\"当前系统用户名"\AppData\Roaming\kingsoft\wps\addons\pool\win-i386\krpt_"版本号"
````
上述文件夹里面有一个名为“krpt.ini”的文本文件，打开会发现里面有一个“MacType.Core”，遂怒删之。
重新启动 WPS 之后，MacType 就能渲染 WPS 了。

<img width="397" alt="image" src="https://user-images.githubusercontent.com/12182730/196034683-38fef5bf-ebb7-404d-8720-c66004237f65.png">

**Comment by snowie2000** [comment]
> 今天晚上微软 Excel 在编辑过程中崩了，搞了小半小时的活几乎全丢。
> 
> 于是又找了个 WPS 出来捣鼓一下。 之前网上流传的“将 WPS 设置成单组件运行模式可以支持 MacType 渲染”的方法已经无效。
> 
> 但是，新版的 WPS 倒是给我们开了一扇窗。根据 snowie 前面的跟踪，WPS 的保护与 krpt 这个 DLL 有关。 经我用磁盘搜索发现，krpt 有一个配置文件，放在如下路径（请根据实际情况替换掉“当前系统用户名”和“版本号”）：
> 
> ```cs
> C:\Users\"当前系统用户名"\AppData\Roaming\kingsoft\wps\addons\pool\win-i386\krpt_"版本号"
> ```
> 
> 上述文件夹里面有一个名为“krpt.ini”的文本文件，打开会发现里面有一个“MacType.Core”，遂怒删之。 重新启动 WPS 之后，MacType 就能渲染 WPS 了。
> 
> <img alt="image" width="397" src="https://user-images.githubusercontent.com/12182730/196034683-38fef5bf-ebb7-404d-8720-c66004237f65.png">

已添加到wiki https://github.com/snowie2000/mactype/wiki/WPS 非常感谢

**Comment by guixin233** [comment]
很有用，十分感谢

**Comment by liuuuuu95** [comment]
> 今天晚上微软 Excel 在编辑过程中崩了，搞了小半小时的活几乎全丢。
> 
> 于是又找了个 WPS 出来捣鼓一下。 之前网上流传的“将 WPS 设置成单组件运行模式可以支持 MacType 渲染”的方法已经无效。
> 
> 但是，新版的 WPS 倒是给我们开了一扇窗。根据 snowie 前面的跟踪，WPS 的保护与 krpt 这个 DLL 有关。 经我用磁盘搜索发现，krpt 有一个配置文件，放在如下路径（请根据实际情况替换掉“当前系统用户名”和“版本号”）：
> 
> C:\Users\"当前系统用户名"\AppData\Roaming\kingsoft\wps\addons\pool\win-i386\krpt_"版本号"
> 上述文件夹里面有一个名为“krpt.ini”的文本文件，打开会发现里面有一个“MacType.Core”，遂怒删之。 重新启动 WPS 之后，MacType 就能渲染 WPS 了。
> 
> <img alt="image" width="397" src="https://user-images.githubusercontent.com/12182730/196034683-38fef5bf-ebb7-404d-8720-c66004237f65.png">

我删掉了但是wps一启动他又重新加回来了，咋整，老哥

**Comment by snowie2000** [comment]
对方软件的防御导致的问题，目前是无法解决的

**Comment by liuuuuu95** [comment]
> 对方软件的防御导致的问题，目前是无法解决的

已解决，删除以后吧那个ini文件设置成只读就好了

**Comment by wmjordan** [comment]
> 我删掉了但是wps一启动他又重新加回来了，咋整，老哥

@liuuuuu95 
抱歉啊，话没说清楚。
“怒删之”的“之”，不是指那个ini文件，是指文件里的“`MacType.Core`”。
