### ISSUE TITLE
Adjust RenderWeight for individual fonts

### ISSUE THREAD

**Issue by IceMan81** [snowie2000/mactype#510]
Is there a way to set different RenderWeights for different fonts - right now I can set the NormalWeight.

**Comment by snowie2000** [comment]
There is a global alphablend table which is initialized by `void CAlphaBlend::init()` from `ft.cpp` line 191.

This table is initialized on demand and affected by 3 parameters: `RenderWeight`, `GammaValue` and `Contrast`, which means if you would like to give an individual value of `RenderWeight` to a font, you should also give it the other two (can be omitted like other individual parameters, of course).

Currently, this alphablend table is unique and is used program-wide. That's because it takes a significant amount of time to initialize it that it will be too slow to initialize many different copies for each font specified.

I believe that the performance impact can be mitigated if all the tables are initialized only when they get used for the first time, and it takes some time to implement it if you think it is indeed useful and affects the overall rendering result very much.

**Comment by IceMan81** [comment]
I think I can live without font specific RenderWeight. I had a situation where one found looked really thick with 
HintingMode=0, AntiAliasMode=4 but did not have the issue with other fonts. And it looked like the right fix was reduce the RenderWeight for the font. 
If I HintingMode=3, AntiAliasMode=2 the font looked much better. But I think I've an explanation for this, the font was in OTF format and hence the rendering was not as expected.

**Comment by sammilucia** [comment]
I think this is beyond the scope of MacType for now and will start to make it too difficult for new users. It's very configurable as-is, also @IceMan81 has said he can live without it. Changing to wontfix and closing.

@snowie2000 please feel free to overrule
