### ISSUE TITLE
Head of capital letter and quotation mark is blurry

### ISSUE THREAD

**Issue by hwooo** [snowie2000/mactype#514]
![cap3](https://user-images.githubusercontent.com/46282492/53404722-97ec5a80-39f9-11e9-82bd-e343abd04f0f.PNG)
![cap4](https://user-images.githubusercontent.com/46282492/53406952-66c25900-39fe-11e9-90ce-314aae31a7a5.PNG)

in IntelliJ IDEA, head of capital letters and quotation marks is displayed as blurry text after enabling MacType.
I'm using 2018.1-beta5 and [Fantasque Sans Mono](https://github.com/belluzj/fantasque-sans) with 16pt. However, I've confirmed that the issue occurs with other fonts, too.
I couldn't find same issue in other editors.(e.g. VS Code, Atom)

**Comment by snowie2000** [comment]
Personally, I believe it's totally normal as the height of the text is a float number that can't be perfectly aligned to the pixel grid all the time.

To force the pixel alignment (or grid fitting), you need to enable hinting.

PS: If you want to ask why the bottom of the text is not blurred, that's because unlike what you may think, the height of the text is actually calculated from the "baseline" of the of a text, which is usually the same line as the bottom line of the letter "x" (or other normalized letters without "tails").

Because of the way the text is positioned, the bottom line of the text is, in most cases, aligned to the grid.

**Comment by hwooo** [comment]
Thank you for detailed answer! How to I enable hinting? Do I have to modify `win7.ini` file?

**Comment by snowie2000** [comment]
Yes, you need to modify your profile.
Please refer to https://github.com/snowie2000/mactype/wiki/HintingMode for possible values.

**Comment by sammilucia** [comment]
Hi, I'm closing this issue as it's normal behaviour of the FreeType and can be disabled with Hinting.

@NDelt please try some other profiles in MacType, especially some of the newer ones (Clean Sharp, Clean Soft, extratype, mufunyo), as they use most of MacType's features, and have a play with the ini file 😊.
