### ISSUE TITLE
Ableton Index Service Not starting

### ISSUE THREAD

**Issue by Br0ckout** [snowie2000/mactype#519]
I'm having an issue where the indexer service (used for indexing and populating files within abletons built in file browser) is not starting. The ableton.exe app launches but its indexer process does not. It works if I add an ableton as an exception to mac type. Is there anyway I can fix this so I can use mactype in Abletons menus?

**Comment by snowie2000** [comment]
Please leave a link to the file browser to me if it's free.  I will try it myself and try to figure it out

**Comment by Br0ckout** [comment]
It’s built into the main ableton app. There’s a free trial of ableton here though https://www.ableton.com/en/trial/

**Comment by Br0ckout** [comment]
You can add folders on your drive to the built in file browser so you can quickly access and find audio samples, when mactype is running they won’t populate your files as the indexer fails to start.

**Comment by snowie2000** [comment]
OK I'll try it out as soon as I have time

**Comment by Br0ckout** [comment]
Thankyou I really appreciate it.

**Comment by snowie2000** [comment]
hmm... It's a complex application... I need your help to operate it.

Thanks.

**Comment by Br0ckout** [comment]
Once the application has launched you will be at a blank project.

On the left hand side of the interface you have a section called “Places” there you can add a folder to it’s built in file browser.

Once you’ve added a folder (preferably one with some audio files in it like wav or mp3), ableton should populate it giving you easy access to those files inside ableton. 

When mactype is running this doesn’t happen, the folder just stay blank inside ableton because it’s indexer process fails to launch. If you add ableton as an exception then try again, it will then populate and you can see its indexer process appear in task manager.

**Comment by snowie2000** [comment]
Should it be something like this?
![QQ截图20190318103950](https://user-images.githubusercontent.com/11767189/54503451-3e2cdf80-496a-11e9-8b75-1856d611da09.png)

And the indexing process seems running properly
![QQ截图20190318104003](https://user-images.githubusercontent.com/11767189/54503515-8946f280-496a-11e9-8446-016ffe543e01.png)

Could you share your profile and your loading mode to me?

**Comment by Br0ckout** [comment]
Hmmm that’s odd.

I’ll have to double check when I’m back at my desktop tomorrow but I was using the default profile with mactype loading as a process in the system tray + admin privilege. I also tried running as a reg but also didn’t work.

I’m running Windows 10 x64 1809

**Comment by snowie2000** [comment]
MacType does have some weird problems with W10+UAC. I haven't worked it out so far.

I may try the ableton in Windows10 later.

**Comment by Br0ckout** [comment]
Ok thanks for your help so far.

**Comment by Br0ckout** [comment]
Hope you're well. Any further advice at all on how I could fix this?

Thanks.

**Comment by sammilucia** [comment]
@Br0ckout please see my https://github.com/snowie2000/mactype/issues/426#issuecomment-481053738 as I believe this might be fixed in the latest beta of Live. Please let us know?

**Comment by sammilucia** [comment]
I'm just closing this issue as I've integrated it into issue #426, as I'm (hopefully) starting my usual clean up of issues so @snowie2000 can focus. However please let us know how you go with Live beta!

**Comment by snowie2000** [comment]
![ableton](https://user-images.githubusercontent.com/11767189/57216335-2694dd80-7022-11e9-8556-42ebf7300bcd.png)
Finally solved the problem and yes, it is a problem that only occurs in Windows 10 because of its new security enhancement and yes, this is an important bug.

I'm trying to explain it simply.
The way MacType injects into other processes is based on an assumption (which is always true in Windows version earlier than 10) that the system dlls such as `kernel32.dll`, `kernelbase.dll` and `ntdll.dll` will be always loaded into the same image base and the functions exported by these system DLLs are at the same address.
Which is, sadly, changed in Windows 10. 

For some unclear reason, Windows 10 will do [ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization) to system DLLs, but not in all cases.
It only does ASLR for certain applications in which, the `Ableton indexer` is included.

I have updated the loader part and mt64agnt.exe and looks like it's working now.

I think it may be related to some chrome crashes.

**Comment by Br0ckout** [comment]
This is great thankyou! Do I just download the latest build?
