### ISSUE TITLE
MacType - Can't' Live without it, can't live with it

### ISSUE THREAD

**Issue by cricrazy** [snowie2000/mactype#529]
I love MacType. I really love how it renders the fonts on Windows. It looks absolutely amazing. 

However, I keep fighting with Windows applications to make MacType work. 

Office applications are the most stubborn ones, Outlook, Word, PowerPoint that I work a lot on keeps failing to render MacType fonts. 

I also noticed that if I do not shutdown my computer, but keep it a sleep mode at the end of the day. Next day, the MacType rendering is a hit and a miss. 

I just wanted to share my burden and heartache here. Please like/comment if you agree. 

I suppose, **MacType is a (Font) Hero that Windows Need, But the one that Windows does not deserve.** 

Peace.

**Comment by sammilucia** [comment]
Hi @cricrazy, I'm sorry for the long delay in replying, @snowie2000 and I have both been busy on other projects which sometimes happens.

MacType should not cause any problems when you wake from sleep. Even though we call it a beta, it's a stable, mature product. We call it a beta because we are being cautious, because of the nature of what we are dong (replacing and overriding the Windows font engines!)

1. Are you able to provide more information about which apps specifically you're having problems with after sleep? Or is it perhaps certain types of apps (for example, it might be just Windows UWP apps, or Control Panel apps?) that cause a problem?

2. Microsoft Office 2013 is a problem - Office 2013 doesn't use DirectWrite or GDI - it uses its own font rendering, so there is no way of replacing its fonts. Why Microsoft decided to do this is beyond us. The solution is to upgrade to Office 365 (Office 2016, now currently updating to Office 2019). Also see https://github.com/snowie2000/mactype/issues/365 for more detail on this issue.

3. If you're already using Office 365 (2016/2019) then please make sure you're using https://github.com/snowie2000/mactype/releases/tag/2018.1-beta5, and try using one of the newer profiles (extratype, mufunyo, clean sharp, clean soft) which use all of the new DirectWrite parameters.

4. You should also ensure you're running in Tray Mode (Administrator), or Service Mode ... OR you can run it in Registry Mode, but only with Secure Boot disabled (see: https://github.com/snowie2000/mactype/wiki/Secure-Boot). This isn't a MacType thing.

Please let me know if you still have problems.

**Comment by derekxia1988** [comment]
> Hi @cricrazy, I'm sorry for the long delay in replying, @snowie2000 and I have both been busy on other projects which sometimes happens.
> 
> MacType should not cause any problems when you wake from sleep. Even though we call it a beta, it's a stable, mature product. We call it a beta because we are being cautious, because of the nature of what we are dong (replacing and overriding the Windows font engines!)
> 
> 1. Are you able to provide more information about which apps specifically you're having problems with after sleep? Or is it perhaps certain types of apps (for example, it might be just Windows UWP apps, or Control Panel apps?) that cause a problem?
> 2. Microsoft Office 2013 is a problem - Office 2013 doesn't use DirectWrite or GDI - it uses its own font rendering, so there is no way of replacing its fonts. Why Microsoft decided to do this is beyond us. The solution is to upgrade to Office 365 (Office 2016, now currently updating to Office 2019). Also see #365 for more detail on this issue.
> 3. If you're already using Office 365 (2016/2019) then please make sure you're using https://github.com/snowie2000/mactype/releases/tag/2018.1-beta5, and try using one of the newer profiles (extratype, mufunyo, clean sharp, clean soft) which use all of the new DirectWrite parameters.
> 4. You should also ensure you're running in Tray Mode (Administrator), or Service Mode ... OR you can run it in Registry Mode, but only with Secure Boot disabled (see: https://github.com/snowie2000/mactype/wiki/Secure-Boot). This isn't a MacType thing.
> 
> Please let me know if you still have problems.

Great job! I'm using Mactype for more than ten years, happy to see it is still upgrating:kissing_heart:

**Comment by snowie2000** [comment]
It's still running and we are planning to release a new version in the next few days. Stay tuned.
Thank you for being with us.

**Comment by sammilucia** [comment]
@cricrazy please try the new beta6 here https://github.com/snowie2000/mactype/releases/tag/2019.1-beta6. I will close this issue as we believe it's resolved however if we can be of any further help please let us know.
