### ISSUE TITLE
Can't run Forza:Horizon4 with MacType

### ISSUE THREAD

**Issue by Ironman998** [snowie2000/mactype#531]
I've add`[UnloadDll]
ForzaHorizon4.exe` to MacType.ini and ini/IOS.ini.
But the game still can't run.
My MacType version is beta5.

**Comment by snowie2000** [comment]
Ok, there is one thing I think I should mention.

Add an application to `[UnloadDll]` doesn't always mean the application won't be affected by MacType (unless you're in registry mode), since MacTray.exe isn't monitoring the profiles changes.
If you added the exception by hand, you have to restart mactray.exe to make it aware of your list changes so that it wouldn't try to load into your excluded applications.

**Comment by Ironman998** [comment]
After restart I still can't open the game.(and I tried registry mode, it still don't work)
I don't know what the problem is.
This is my .ini file below, I'm really grateful for your help.
### Mactype.ini
`[General]
AlternativeFile=ini\iOS.ini

[MacType]
RedrawDelay=5000
AutoEnable=1
HideDenied=1
AutoUnload=1
AutoRun=0
LoadType=1
Use64Agent=1
HideACD=1
Language=0

[UnloadDll]
VBoxSvc.exe
VirtualBox.exe
ForzaHorizon4.exe
Spotify.exe
`

**Comment by snowie2000** [comment]
I didn't see any misconfiguration in your profile.

Maybe you'd like to give my new loader a try, see if it saves your game.
[MacType-new-injector-050719.zip](https://github.com/snowie2000/mactype/files/3151242/MacType-new-injector-050719.zip)

Usage: unzip and overwrite.

**Comment by Ironman998** [comment]
THANK YOU!! It really works after I replace these files.

**Comment by snowie2000** [comment]
Glad it helps. 
So what’s the status of your game shown in the mactray process manager? Ignored or running ?

**Comment by Ironman998** [comment]
It's access denied.

**Comment by snowie2000** [comment]
🤣 that’s really unexpected
