### ISSUE TITLE
FontNameCache is too small

### ISSUE THREAD

**Issue by wzv5** [snowie2000/mactype#577]
https://github.com/snowie2000/mactype/blob/a97f418c6110b08f7e693b314d8c38cbf8788bc6/settings.cpp#L13

The default size is 100, it's too small. In my system, this size is 321 (only system fonts).

My original intention was to create a PR, but when I looked at `hash_list`...... It's too terrible...... I don't know if it's a good idea to continue using it. I'd like to use `std::unordered_map` (C++11) to instead, is it okay to use C++11 in this project? @snowie2000 

This issue I will not submit PR, waiting for author to fix it.

**Comment by snowie2000** [comment]
It looks terrible because it is a port of `THashedStringList` from Delphi. In this implementation, the size only affects the speed of lookup instead of the items it can store. In normal systems, size 100 is speedy enough.

**Comment by wzv5** [comment]
Well, it's really not a big problem, it just affects the initialization speed.
（能加个作者的QQ或者其他什么聊天帐号么？还有一些问题希望能方便交流，我的联系方式就在 github 个人介绍里）

**Comment by snowie2000** [comment]
The FontNameCache is used during the whole lifespan of MacType to convert any font name to its localized name so that `SimSum` and `宋体` can be identified as the same font. So the speed matters. I was planning to migrate to std::map but was too lazy to start, though...

You could always contact me by Google Hangouts. My email in my bio is also my hangouts account.
