### ISSUE TITLE
Updater broken on XP, XP x64 & Server 2003

### ISSUE THREAD

**Issue by GrandAdmiralThrawn** [snowie2000/mactype#579]
Currently, updater.exe is broken on all NT5 platforms. I'm not sure if I'm correct, but it appears it wants to use WinSSL / SChannel, and the one on XP is just too old (cryptographic protocol & cipher support from the stoneage ;) ).

Not sure if I'm correct there, but here's the error that happens, when you try to launch updater.exe:

![updater-error](https://user-images.githubusercontent.com/12556133/61218568-9efad780-a712-11e9-87a4-b85b2d5bf4e1.png)

*If* I'm correct, it would help to link MacType against modern OpenSSL or GnuTLS instead of Windows SSL (that might be too much work though I guess).

**Comment by snowie2000** [comment]
I already knew the problem. 
You are right. It's because the cryptographic suite in the XP is way too old, and it doesn't support sending SNI in https.
Our update server is using Cloudflare and the XP support is not available in its free plan. I was planning to solve the problem before its final release and what I would like to try is to enable HTTP partially for the website so that the update info could be retrieved via HTTP instead of https.

We can't compile the updater with OpenSSL or GnuTLS because the updater itself is actually part of the Advanced installer - mactype's previous installer tool. Because it seems working fine alone and it has a builtin multi-language support, we "borrowed" it from the AI but turned out that it relies on the WinSSL.

**Comment by snowie2000** [comment]
Fixed. The updater should work correctly in the Xp and server 2003 now.

**Comment by GrandAdmiralThrawn** [comment]
Confirmed working!

Thank you very much!
