### ISSUE TITLE
Programs don’t open anymore

### ISSUE THREAD

**Issue by tunamayo04** [snowie2000/mactype#665]
I have just downloaded mactype and as soon as the install finished, my PC became unable to open programs. The only ones that seem to work are Task Manager and File Explorer. I really don’t understand what’s going on and am getting desperate. Is this a known issue? Is there any fix?

**Comment by sammilucia** [comment]
hi @zerox029 

I'm sorry you're having this problem. No it's not a known issue, MacType is pretty clear of major issues, however the first thing I suspect it's your antivirus is conflicting with MacType (because MacType injects into every program). you could try disabling your antivirus temporarily to see if that helps.

If it does, you should be able to exclude MacType from real-time scanning. Let us know how you go or if you need help 😊

**Comment by tunamayo04** [comment]
That might be the case, I realized that running programs as administrator seemed to fix the issue. But I've just uninstalled Mactype for now. Thank you for your help!
