### ISSUE TITLE
Titlebars of many apps (Notepad etc.) don't use Mactype

### ISSUE THREAD

**Issue by taprobane99** [snowie2000/mactype#768]
Hi,

I've noticed that both the unreleased .dll posted in 2020 on here, and the recent RC1 package don't render titlebars of many apps using Mactype, whereas using the 2019 version does. This is with a completely clean install after removing everything from 2019.

Can this be fixed? Armbreaker and toggling service/tray mode don't seem to have any effect.

With 2019 I was running registry mode so that could be the difference.

**Comment by snowie2000** [comment]
[MacType621-hotfix.zip](https://github.com/snowie2000/mactype/files/6684723/MacType621-hotfix.zip)
Here is a quick patch for it.
The titlebars didn't get rendered in this version because the process privilege detection routine got updated and it's more conservative. Now it checks for `dwm.exe` exclusively and should work on titlebars.

**Comment by taprobane99** [comment]
thanks. can confirm it works fine.

**Comment by ChicoThorn** [comment]
Thank you @snowie2000 and @taprobane99 — it works for me too. 😊
