### ISSUE TITLE
服务模式渲染不及时

### ISSUE THREAD

**Issue by ghost** [snowie2000/mactype#775]
为了响应微软的 Secure Boot 不得不从注册表改为服务模式，但是服务模式有时候渲染不及时，有点影响体验。

### 系统环境
* Windows 10 21H1 (19043.928)
* MacType 2021 服务模式
* 安全启动 - 启用
* MyDockFinder v5.9.9.86（仿苹果 Dock）
    > 题外话，MacType 会让 MyDockFinder 经常卡死，所以在 MacType 中设置了 UnloadDll 为 Dock_64.exe。以及这是 MyDockFinder 的官网 https://www.mydockfinder.com/ 为 Dock_64.exe 进程 UnloadDll 后，MyDockFinder 工作很稳定。转储文件：https://cowtransfer.com/s/03a9ff7f72954b
* Notepad3 v5.21.227.1

### 复现步骤
1. 为电脑启用“安全启动”功能，并设置 MacType 为服务模式，然后重启电脑；
2. 从 MyDockFinder 中启动 Notepad3；
    > 题外话，不从 MyDockFinder 启动也会复现，所以和这个也没什么关系。另外除了 Notepad3 也有其他程序比如 QQ、微信都能复现，只是概率稍微低一点。甚至资源管理器都能复现。
3. Notepad3 菜单栏并没有得到渲染，只有鼠标滑过才会被渲染。

![动画.gif](https://i.loli.net/2021/06/28/LYv2UIDzkR8wbHx.gif)

**Comment by snowie2000** [comment]
For now, no known method has been found to force a window redraw or update from a service, so you have to hover to make the window repaint itself.

To avoid this problem, add your launcher to `exclude` instead of `unloaddll`. 

I've checked your dump, and there is a deadlock with DirectWrite. Due to my oversight, the file easyhk64.dll was not built with debug info so I can't see more meaningful information in your dump. I'll upload a new dll later and please kindly test it and do a process dump.

Also, the deadlock that happened in the DirectWrite indicates that disabling Directwrite support for FindMyDock should solve your problem as well.

**Comment by snowie2000** [comment]
Hmm, turns out my version of easyhook is built with symbol and you're using your customized version.
Please restore to the official version, do not use easyhook from any other sources.

**Comment by ghost** [comment]
经检查，发现电脑 System32 与 SysWow64 留有第三方 EasyHook 文件 😂
> 这可能是从 “MacType 2019 第三方版”升级到“MacType 2021 官方版”残留的文件

删除残留的文件以及 MacType 安装目录后重新安装后，即便不为 MyDockFinder 进行 UnloadDll 操作，也不会导致 MyDockFinder 崩溃了 😄👍 可能我的另外一个 issue #773 也与此有关，但目前已经退回 21H1 已经无法得到印证。

关于服务模式渲染慢的问题，我暂时关闭主板安全启动，使用注册表模式进行渲染 😸 

非常感谢雪大抽时间分析与答复，问题已经完美解决。
