### ISSUE TITLE
Missing/weird font using ChicoThorn

### ISSUE THREAD

**Issue by uncttao** [snowie2000/mactype#855]
**Issue**:

Two outstanding issues are the following (using **ChicoThorn** font, **tray** mode, Windows 11).

First, in VS Code, the left-hand side menu icons are mostly broken.

![image](https://user-images.githubusercontent.com/7554653/164862868-947d0931-0529-4d9c-9afe-7b5ba3b0d9e0.png)

Second, some fonts in the browser (chromium Edge, version 100+) look horrible. Notice how the text in the search box is unusually narrow. It seems to impact the _default_ font in the browser.

![image](https://user-images.githubusercontent.com/7554653/164863074-28df782e-1279-49f3-a1f4-ac4f4f194cdb.png)

This issue seems to be unique for ChocoThorn. I do not recall other fonts have this problem.

**Comment by sammilucia** [comment]
hi, I think this might be a problem with the font encoding for that font. thoughts @ChicoThorn ?

**Comment by ChicoThorn** [comment]
> hi, I think this might be a problem with the font encoding for that font. thoughts @ChicoThorn ?

Hi @sammilucia , I'm not sure what exactly is being referred to here... the ChicoThorn (original) INI file or the most recent ChicoThorn Sharp INI file? Or is it referring to the customized Segoe UI font that I uploaded a while back? If it's referring to the customized Segoe UI font, then I recommend using the standard Segoe UI font supplied by Microsoft. When I added my custom glyphs I used cell positions utilized by characters with diacritical marks (which I personally never used anyway). I did this rather than adding my own new glyph cells because of the limitations of the 1252 code page used by Windows in filenames, and other system apps, etc. If a non-1252 glyph is used in a filename there are some functions in Windows that will not work properly. I think this is just a legacy problem that they haven't resolved yet. Mostly Unicode characters work nearly everywhere in the system, but in some cases they don't, hence my use of diacritical glyph cells for my customizations. Mostly those customizations are for my own use anyway, so others should just use the standard Segoe UI font.

If the problem is referring to the INI file, then the problem probably lies in the font substitutes I use. Some being dependent on 3rd party fonts (Liberation Mono, Noto Serif, Noto Sans, etc.) If this is the case then I'd recommend just removing those substitutions. My main goal in the font substitutions I use was to have a (mostly) unified font for use everywhere in the UI. I chose Segoe UI as that font since it's the predominant font already used by Windows. I am aware of some issues with that, especially when using system scaling or text scaling. For example at some scaling sizes the standard Windows color picker won't accept the necessary 3 digits for RGB values. I've tested pretty much every scaling size for this particular issue (ranging from 125% to 175%) and found that on my monitor (1560 x 1440 [2K]) the sizes 150%, 155%, 158%, 163%, 164% work the best. Currently I'm using 164% scaling as that seems to work the very best overall. 

As for the browser display issue, I've seen that a few times myself on some websites, but not on most. I've thought it must be a font substitute issue, but I've not been able to track down the name of that narrow font that displays. When I do, I'll update my font subs list to include it. 

Additionally, I've done a lot of work on the font substitutions list over the past two years, which is not reflected in the original ChicoThorn INI file that is currently included with MacType. Perhaps using the most recent version of ChicoThorn would help? (Please note, I've dropped the 'Sharp' from the filename and am calling it simply ChicoThorn.ini now. It comes in two versions: ChicoThorn.ini which contains fewer Font Substitutions (no 3rd party fonts), and ChicoThorn+.ini which contains all my current Font Substitutions including 3rd party fonts. I use ChicoThorn+ myself. The INI files are attached below:

[ChicoThorn INIs.zip](https://github.com/snowie2000/mactype/files/8546650/ChicoThorn.INIs.zip)

If the problem refers to something else, then please give me some more information so I can work on correcting it. Also, any suggestions anyone may have would be more than welcome! — Thanks for bringing this to my attention Samantha. 🙂

**Comment by uncttao** [comment]
@ChicoThorn Thanks for your reply! I tried the ChicoThorn+ file, but unfortunately, it solves none of the issues listed except for making some font thicker.

I am persisting over this because ChicoThorn has such an outstanding rendering quality on my laptop that no other suppliers compare. I really wish it could work fully.

**Comment by ChicoThorn** [comment]
> I tried the ChicoThorn+ file

Hi @uncttao, Thanks for your feedback. I'll do some experimentation testing on the VS Code app as well as Edge Chromium (I'm using Edge Canary, the nightly version of Edge Chromium)  to see if I can solve the two issues you mentioned, the missing glyphs that are being replaced with boxes and the browser display of that narrow font. I'll get back to you here soon, when I have some results.

**Comment by ChicoThorn** [comment]
Hi @uncttao and @sammilucia! Okay, I made a test copy of my most current ChicoThorn.ini (Version 2022.04.20) and removed ALL of my font substitutions. After restarting my computer, I opened VS Code (most recent version) and all of the missing glyphs displayed perfectly! Then I opened a website I use frequently that had been displaying that overly narrow font you mentioned, and it too rendered correctly; no narrow font! — This all indicates to me that the problem does indeed lie in my font substitutions list. I will conduct further tests to see if I can nail down exactly which font substitutions are causing the problem and will then upload my results as well as an updated ChicoThorn.in file.

Below are screenshots of my test results:

![VS Code - All Font Subs OFF](https://user-images.githubusercontent.com/27825631/164948890-657e5b06-e4ea-4b1a-9e1a-f27aec264f8e.png)

![Browser MFP - All Font Subs OFF](https://user-images.githubusercontent.com/27825631/164948898-853ea448-77ad-4ac6-bebf-4b53071ed80d.png)

**Comment by ChicoThorn** [comment]
Hi @sammilucia, and @uncttao — Been testing... and I think I found the culprit: the font substitute: "arial=Segoe UI" .  I will update my INI soon and upload the changes, but in the meantime, just put a semi-colon in front of that entry in the INI file and it should work fine. If you still experience the squares in VS Code, then also disable the font substitute: "Segoe UI=Segoe UI" — When I first tested I had to disable both for VS Code to work, but when I came back to it today, it worked fine leaving the "Segoe UI=Segoe UI" enabled. 🤷 Give this a shot, and see if it works for you too. 🙂

**Comment by RobbedColek** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/24840151/165791364-4652dc4a-d7ac-44cd-b1d4-c770530866a9.jpg)

I am having similiar issue with "Arial=Segoe UI" in Steam application.

**Comment by uncttao** [comment]
@ChicoThorn Amazing findings. Thanks! I tested your proposed modification to the ini by adding a semicolon in the beginning of the "arial" line. I can confirm this solved both of my issues! There is no need for me to remove the "Segoe" line for everything to work. Looking forward to the official release!
