### ISSUE TITLE
GNU Octave font rendering with MacType

### ISSUE THREAD

**Issue by perdrix52** [snowie2000/mactype#863]
[https://octave.discourse.group/t/octave-font-rendering-with-mactype/2722](url)

**Comment by snowie2000** [comment]
First thing first, as I always said, ClearType should be turned on all the time despite you like it or not. Because it heavily changes the way Windows GDI API works, and MacType relies on the exact behavior of it 'cause we have no known way to alter it besides turning on ClearType.

Secondly, if you have clipboxfix off, turn it back on. It may help.

**Comment by perdrix52** [comment]
My bad - I was under the impression it was an either ClearType or MacType choice.   So I should have both active?

**Comment by snowie2000** [comment]
Definitely.

**Comment by MarkDraconian** [comment]
Oh wow, i was using Mactype the wrong way all this time, because i was just leaving it on and ClearType always turned off.
Noticed a really good improvement with Firefox text rendering!
