### ISSUE TITLE
Breaks Windows 10 OS - Slows Entire PC Startup To Ridiculous Level

### ISSUE THREAD

**Issue by stylemessiah** [snowie2000/mactype#913]
WOW, installing Mactype on Windows 10 21H2 just now and rebooting, it literally ground startup processes to molasses...it took a full 5 minutes for the system tray to appear

Even trying to access task manager to try and kill its service took 6 minutes

This is what i would call a showstopper folks, how does this pass testing?

Event Viewer shows it faulting dllhost (A LOT)

Uninstalled

**Comment by casef** [comment]
Pass testing? I'm not sure you fully understand you're dealing with what is essentially an experimental utility made more or less by a single person in their spare time. It's not an official/commercial software made by a big development team with a dedicated QA department.

And since it's more than likely other people are using MacType on Win 10 21H2 just fine, you might've simply encountered some kind of unstability specific to your system.

**Comment by snowie2000** [comment]
Not sure what version you were on. Could be totally normal if you were using any version older than RC1 because that is the first version that complies with shadowstack spec. Without it, most Windows system applications will crash (giving you are not using an ancient CPU that doesn't support shadowstack).

My system is on Win10 LTSC 21H2 too, everything is just working fine.

**Comment by stylemessiah** [comment]
Was using latest version and no joke didnt get a taskbar for 6 whole minutes, tested over multiple reboots

Removing the app immediately returned Windows to a working state as before

Very weird stuff.

Worth pointing out ive used in in previous years without issue.
