### ISSUE TITLE
service mode

### ISSUE THREAD

**Issue by ghost** [snowie2000/mactype#951]
How does the service mode realize and work? Do you have an introduction to the principle? Thank you very much!
(Appinit_DLLs has been deactived by Secure Boot as far as i know)

**Comment by snowie2000** [comment]
Service mode is basically the mactray.exe tray mode, but running as a service.

When running as a service, it has the ability to access every user logged in to the system and has a slighter higher privilege to access more processes. 

And as a service, it always has the administrator right despite what UAC setting is, which is quite important since with UAC on, users can't start an elevated process on startup easily.
